
spring:
  application:
    name: Appointment-Service

  datasource:
    url: jdbc:mysql://localhost:3306/appointmentDB
    username: root
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show: true

# kafka Config
  #Producer config
  kafka:
    producer:
      bootstrap-server: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer

server:
  port: ${SERVER_PORT}

secret:
  header:
    key: ${SECRET_HEADER_KEY}

# To-Do :- Make this eureka Configurable
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health,info,circuitbreakers






